#!/usr/bin/env node

/**
 * Generates a TypeScript file listing all achievement image filenames
 * from the /public/ach/ directory.
 *
 * Usage: node scripts/ach_img_names.js
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const PUBLIC_ACH_DIR = path.join(__dirname, '../../public/ach');
const OUTPUT_FILE = path.join(__dirname, '../data/generated/achievementImages.ts');

function generateAchievementImages() {
    // Ensure the public/ach directory exists
    if (!fs.existsSync(PUBLIC_ACH_DIR)) {
        console.error(`Error: Directory ${PUBLIC_ACH_DIR} does not exist`);
        process.exit(1);
    }

    // Read all files from the directory
    const files = fs.readdirSync(PUBLIC_ACH_DIR);

    // Filter for files starting with "ach" and remove extensions
    const achFiles = files
        .filter(file => file.startsWith('ach') && file.endsWith('.png'))
        .map(file => file.replace('.png', ''))
        .sort();

    console.log(`Found ${achFiles.length} achievement images`);

    // Ensure output directory exists
    const outputDir = path.dirname(OUTPUT_FILE);
    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    // Generate the TypeScript file content
    const content = `// Auto-generated by scripts/ach_img_names.js
// Do not edit manually - run 'node scripts/ach_img_names.js' to regenerate

export const achievementImages = [
${achFiles.map(name => `    "${name}"`).join(',\n')}
];
`;

    // Write the file
    fs.writeFileSync(OUTPUT_FILE, content, 'utf8');
    console.log(`Generated ${OUTPUT_FILE}`);
    console.log(`Listed images: ${achFiles.join(', ')}`);
}

generateAchievementImages();
